# Generated by Django 5.2.4 on 2025-08-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventorylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorylog",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("INITIAL", "Initial Stock"),
                    ("RESTOCK", "Restock"),
                    ("SALE", "Sale"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("RETURN", "Return"),
                ],
                max_length=50,
            ),
        ),
    ]
